config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  root "posts#index"
  devise_for :users
  namespace :account do
    resources :posts
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: :user_id
  belongs_to :post, counter_cache: :comments_count
  validates :content, presence: true

  def editable_by?(user)
    user == author
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :author, class_name: "User", foreign_key: "user_id"
  has_many :comments, :dependent => :destroy

  def editable_by?(user)
    user == author
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/account/comments_controller.rb
class Account::CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = current_user.comments.all.order("created_at DESC")
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.all.order("created_at DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_paramrters, if: :devise_controller?

  protected

  def configure_permitted_paramrters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to post_path(@post), notice: "新增評論成功！"
    else
      redirect_to post_path(@post), alert: "新增評論失敗！"
    end
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: "更新評論成功！"
    else
      redirect_to post_path(@post), alert: "更新評論失敗！"
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), alert: "刪除評論成功！"
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_path(@post), notice: "新增文章成功！"
    else
      render :new
    end
  end

  def show
    @comments = @post.comments.all.order("created_at DESC")
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(@post), alert: "更新文章成功！"
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path, alert: "刪除文章成功！"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/account/comments_helper.rb
module Account::CommentsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger}

    close_button_options = {class: "close", :type => "button", "data-dismiss" => "alert", "aria-hidden" => true}
    close_button = content_tag(:button, "x", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"
      content_tag(:div, alert_content, class: alert_class)
    end
    alerts.join("\n").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
= simple_form_for [@post, @post.comments.build] do |f|
  = f.input :content, input_html: {class: "form-control"}
  = f.submit "Submit", class: "btn btn-primary"

app/views/comments/edit.html.haml
.col-md-4.col-md-offset-4
  %h1 修改評論
  %hr

  = simple_form_for [@post, @comment] do |f|
    = f.input :content, input_html: {class: "form-control"}
    = f.submit "Submit", class: "btn btn-primary"

app/views/common/_footer.html.haml
%footer.container{:style => "margin-top: 100px;"}
  %p.text-center Build by Rorusage

app/views/common/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{:type => "button", "data-toggle" => "collapse", "data-target" => "#example-navbar-collapse"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.navbar-brand{:href => "/"} Forum

    .collapse.navbar-collapse{:id => "example-navbar-collapse"}
      %ul.nav.navbar-nav.navbar-right
        - if !user_signed_in?
          %li= link_to("Sign up", new_user_registration_path)
          %li= link_to("Log in", new_user_session_path)
        - else
          %li.dropdown
            %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"}
              Hi, #{current_user.name}
              %b.caret
            %ul.dropdown-menu
              %li= link_to("New Post" ,new_post_path)
              %li= link_to("Edit account", edit_user_registration_path)
              %li= link_to("My posts", account_posts_path)
              %li= link_to("My comments", account_comments_path)
              %li= link_to("Log out", destroy_user_session_path, method: :delete)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render "common/navbar" %>
  <%= notice_message %>
  <%= yield %>
</div>

<%= render "common/footer" %>

</body>
</html>

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  .form-group
    = f.input :title, input_html: {class: "form-control"}
    = f.input :content, input_html: {class: "form-control"}
  = f.submit "Submit",  class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/posts/edit.html.haml
.col-md-4.col-md-offset-4
  %h1 修改文章
  %br

  = render "form"

app/views/posts/index.html.haml
.col-md-12
  - @posts.each do |p|
    %h1= link_to(p.title, post_path(p))
    - if p.editable_by?(current_user)
      = link_to("Edit", edit_post_path(p))
      = link_to("Delete", post_path(p), method: :delete, data: {confirm: "Are you sure?"})
    %h4 #{p.author.name}, published at #{time_ago_in_words(p.created_at)} ago
    %p= truncate(p.content, length: 200)
    %hr

app/views/posts/new.html.haml
.col-md-4.col-md-offset-4
  %h1 新增文章
  %br

  = render "form"

app/views/posts/show.html.haml
.col-md-12
  %h1= @post.title
  = link_to("Back", root_path)
  - if @post.editable_by?(current_user)
    = link_to("Edit", edit_post_path(@post))
    = link_to("Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"})

  %h4 Posted by : #{@post.author.name}
  %h5 Post at #{@post.created_at.strftime("%A %B %d")}
  %hr
  %p= @post.content
  %br
  %h4 #{@post.comments_count} Comments:
  - @comments.each do |c|
    #{c.author.name} said:
    %br
    #{c.content}
    - if c.editable_by?(current_user)
      = link_to("Edit", edit_post_comment_path(@post, c))
      = link_to("Delete", post_comment_path(@post, c), method: :delete, data: {confirm: "Are you sure?"})
    %hr

  = render "comments/comment"